application: uwshudong
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /index.html
  static_files: index.html
  upload: index.html

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /img
  static_dir: img

- url: /.*
  script: main.app
