application: uwshudong
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /img
  static_dir: img

- url: /new
  script: new.app

- url: /.*
  static_files: static/index.html
  upload: static/index.html
